#!/bin/sh
echo "start splat-vo on $HOSTNAME"

DISPLAY="host.docker.internal:0"
export DISPLAY
SAMP_HUB="std-lockurl:file://localhost/root/.samp_${HOSTNAME}"
export SAMP_HUB

./bin/splat/splat -Djsamp.localhost=$HOSTNAME --hub

