FROM openjdk:8-jre-alpine
COPY . /usr/sampbridge
WORKDIR /usr/sampbridge
RUN apk update
RUN mkdir bin &&\
    wget -O bin/jsamp.jar  http://www.star.bristol.ac.uk/~mbt/jsamp/jsamp-1.3.7.jar
CMD ["/usr/sampbridge/sampbridge"]
