FROM openjdk:8
RUN apt-get update; apt-get -y install libxrender1 libxtst6 libxi6
COPY . /usr/topcat
WORKDIR /usr/topcat 
RUN mkdir bin
RUN wget -O bin/topcat-full.jar http://www.star.bris.ac.uk/~mbt/topcat/topcat-full.jar
RUN wget -O bin/topcat http://www.star.bris.ac.uk/~mbt/topcat/topcat
RUN chmod +x bin/topcat
CMD ["/usr/topcat/starttopcat"]
