#!/bin/sh


# host.docker.internal does not work for Linux - 
# run docker with -e $DISPLAY=... instead
#DISPLAY="host.docker.internal:0"
#export DISPLAY

SAMP_HUB=std-lockurl:file://localhost/root/.samp_$HOSTNAME
export SAMP_HUB
#bin/topcat -Djsamp.localhost=${hostname} -hub
bin/topcat -Djsamp.localhost=${hostname} -exthub
